<a href="https://colab.research.google.com/github/sparshap95-tech/ComputerVision/blob/main/Convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ar = np.array([3,5,6,2,1,5])


In [3]:
np.convolve(ar, [1,2,3]) # (3,2,1)


array([ 3, 11, 25, 29, 23, 13, 13, 15])

In [4]:
from sklearn.datasets import load_digits


In [5]:
dt = load_digits(n_class=3)


In [6]:
dt.keys()


dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [7]:
dt.images[0]


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [8]:
dt.images.shape


(537, 8, 8)

In [9]:
X = dt.images
Y = dt.target

In [10]:
X = X.reshape(537,1,8,8)


In [11]:

import torch
import torch.nn as nn
from torch.optim import Adam

In [12]:


X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [13]:
X.shape

torch.Size([537, 1, 8, 8])

In [14]:
model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(64*2*2, 128),
    nn.ReLU(),
    nn.Linear(128, 3)
)

In [15]:


loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)

In [16]:
c=0
for epoch in range(100):
    c=c+1
    opt.zero_grad()
    yp = model(X)
    ls = loss(yp, Y)
    ls.backward()
    opt.step()
    if c%10==0:
      print(ls.item())

0.36468589305877686
0.05838533118367195
0.01288335770368576
0.004022099543362856
0.0018884023884311318
0.00117392186075449
0.0008370295399799943
0.0006451926892623305
0.0005159146385267377
0.00042086016037501395


 Prediction on new data
     

In [17]:
newx = X[112].reshape(1,1,8,8)


In [18]:
newx.shape


torch.Size([1, 1, 8, 8])

In [19]:
Yp = model(newx)


In [20]:
Yp

tensor([[-1.6854,  5.7697, -2.8423]], grad_fn=<AddmmBackward0>)

In [21]:
sx = torch.softmax(Yp, dim=1)


In [22]:
torch.argmax(sx, dim=1)


tensor([1])

Class based Model

In [23]:
class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    self.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
    self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    self.relu = nn.ReLU()
    self.flatten = nn.Flatten()
    self.linear1 = nn.Linear(64*2*2, 128)
    self.linear2 = nn.Linear(128, 3)

  def forward(self, x):
    x = self.conv1(x)
    x = self.relu(x)
    x = self.maxm(x)
    x = self.conv2(x)
    x = self.relu(x)
    x = self.maxm(x)
    x = self.flatten(x)
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    return x

In [24]:
class MyNet(nn.Module):
  def __init__(sf):
    super().__init__()
    sf.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    sf.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
    sf.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    sf.relu = nn.ReLU()
    sf.flatten = nn.Flatten()
    sf.linear1 = nn.Linear(64*2*2, 128)
    sf.linear2 = nn.Linear(128, 3)

  def forward(sf, x):
    print(x.shape)
    x = sf.conv1(x)
    print(x.shape)
    x = sf.relu(x)
    x = sf.maxm(x)
    x = sf.conv2(x)
    x = sf.relu(x)
    x = sf.maxm(x)
    x = sf.flatten(x)
    x = sf.linear1(x)
    x = sf.relu(x)
    x = sf.linear2(x)
    return x

In [25]:


mod = MyNet()

In [26]:

mod(X)

torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])


tensor([[ 0.1284, -0.0327,  0.2044],
        [ 0.1765, -0.0600,  0.0128],
        [ 0.0177, -0.1670,  0.2509],
        ...,
        [ 0.1892, -0.1562,  0.0223],
        [-0.0751, -0.0063,  0.0716],
        [ 0.1359, -0.0623,  0.0972]], grad_fn=<AddmmBackward0>)

In [27]:


loss = nn.CrossEntropyLoss()
opt = Adam(mod.parameters(), lr=0.001)

In [29]:

c=0
for epoch in range(100):
    c=c+1
    opt.zero_grad()
    yp = mod(X)
    ls = loss(yp, Y)
    ls.backward()
    opt.step()
    if c%10==0:
      print(ls.item())

torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
0.1463085263967514
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 1, 8, 8])
torch.Size([537, 32