<a href="https://colab.research.google.com/github/sparshap95-tech/ComputerVision/blob/main/Convolution1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



***Below Code is doing***

Learning convolution (basic with NumPy)

Loading image dataset

Building CNN

Training filters automatically

Extracting features using convolution

Classifying digits (0,1,2)


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ar = np.array([3,5,6,2,1,5])


In [3]:
np.convolve(ar, [1,2,3]) # (3,2,1)


array([ 3, 11, 25, 29, 23, 13, 13, 15])

**Covolution On the Images from load_digits**

In [4]:
from sklearn.datasets import load_digits


In [5]:
dt = load_digits(n_class=3)


In [6]:
dt.keys()


dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [7]:
dt.images[0]


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [8]:
dt.images.shape


(537, 8, 8)

In [9]:
X = dt.images
Y = dt.target

In [10]:
X = X.reshape(537,1,8,8)


In [11]:

import torch
import torch.nn as nn
from torch.optim import Adam

In [12]:


X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [13]:
X.shape


torch.Size([537, 1, 8, 8])

In [14]:
model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(64*2*2, 128),
    nn.ReLU(),
    nn.Linear(128, 3)
)

In [15]:

loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)


In [16]:
c=0
for epoch in range(100):
    c=c+1
    opt.zero_grad()
    yp = model(X)
    ls = loss(yp, Y)
    ls.backward()
    opt.step()
    if c%10==0:
      print(ls.item())

0.2621641159057617
0.04018319770693779
0.010705006308853626
0.004003787878900766
0.0022237002849578857
0.0014693374978378415
0.0010906177340075374
0.0008772637811489403
0.0007262192666530609
0.0006141967605799437


**Prediction on new data**


In [17]:
newx = X[112].reshape(1,1,8,8)


In [18]:
newx.shape


torch.Size([1, 1, 8, 8])

In [19]:
Yp = model(newx)


In [20]:
Yp

tensor([[-4.4302,  6.1116, -2.7346]], grad_fn=<AddmmBackward0>)

In [21]:
sx = torch.softmax(Yp, dim=1)


In [22]:
torch.argmax(sx, dim=1)


tensor([1])