<a href="https://colab.research.google.com/github/sparshap95-tech/ComputerVision/blob/main/digit_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_digits


In [2]:
dt = load_digits(n_class=3)


In [3]:
images = dt.images


In [4]:
Y = dt.target


In [5]:
images[-2]


array([[ 0.,  0., 15., 13.,  1.,  0.,  0.,  0.],
       [ 0.,  0., 14., 14.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  4., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 11., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  1., 16.,  8.,  6.,  5.,  0.],
       [ 0.,  0., 13., 16., 16., 16., 14.,  0.],
       [ 0.,  0., 10., 13., 10.,  6.,  2.,  0.]])

In [6]:
Y[-2]


np.int64(2)

In [7]:
images[0].reshape(1, 64)


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [8]:
images.shape

(537, 8, 8)

In [9]:
X = images.reshape(-1,64)


In [10]:
X.shape


(537, 64)

In [13]:

import torch
import torch.nn as nn
import torch.optim as optim

In [14]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [54]:
model = nn.Sequential(
    nn.Linear(64, 64),
    nn.ReLU(),
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 3)
)

checking the model

In [55]:
model(X)

tensor([[-0.7019, -0.8901,  0.0606],
        [-0.6802, -1.5201, -0.4274],
        [-0.7501, -1.1736,  0.2288],
        ...,
        [-0.2023, -1.7293, -0.6661],
        [-0.3406, -1.2305, -0.7523],
        [-0.7404, -1.3198,  0.0436]], grad_fn=<AddmmBackward0>)

In [57]:
nn.NLLLoss()

NLLLoss()

In [58]:
lossfn = nn.CrossEntropyLoss()


In [59]:
opt = optim.Adam(model.parameters(), lr=0.01)


Training

In [60]:
for _ in range(100):
    opt.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    opt.step()
    print(loss)

tensor(1.4241, grad_fn=<NllLossBackward0>)
tensor(1.3772, grad_fn=<NllLossBackward0>)
tensor(0.6076, grad_fn=<NllLossBackward0>)
tensor(0.5043, grad_fn=<NllLossBackward0>)
tensor(0.3478, grad_fn=<NllLossBackward0>)
tensor(0.1823, grad_fn=<NllLossBackward0>)
tensor(0.1305, grad_fn=<NllLossBackward0>)
tensor(0.1188, grad_fn=<NllLossBackward0>)
tensor(0.0735, grad_fn=<NllLossBackward0>)
tensor(0.0529, grad_fn=<NllLossBackward0>)
tensor(0.0502, grad_fn=<NllLossBackward0>)
tensor(0.0335, grad_fn=<NllLossBackward0>)
tensor(0.0195, grad_fn=<NllLossBackward0>)
tensor(0.0166, grad_fn=<NllLossBackward0>)
tensor(0.0158, grad_fn=<NllLossBackward0>)
tensor(0.0108, grad_fn=<NllLossBackward0>)
tensor(0.0069, grad_fn=<NllLossBackward0>)
tensor(0.0064, grad_fn=<NllLossBackward0>)
tensor(0.0064, grad_fn=<NllLossBackward0>)
tensor(0.0046, grad_fn=<NllLossBackward0>)
tensor(0.0027, grad_fn=<NllLossBackward0>)
tensor(0.0021, grad_fn=<NllLossBackward0>)
tensor(0.0022, grad_fn=<NllLossBackward0>)
tensor(0.00

In [61]:
model(X)


tensor([[ 18.1887, -15.7062,  -9.5686],
        [-16.8386,  17.2887,  -7.3543],
        [-18.1537,   0.0239,  10.8152],
        ...,
        [-23.7042,  -3.0099,  17.0672],
        [-18.2379,  -0.8455,  11.2461],
        [ 19.6194, -15.5865, -11.6320]], grad_fn=<AddmmBackward0>)

Testing

In [62]:
pip install opencv-python


In [63]:
import cv2

In [64]:
ar = cv2.imread('/content/image.jpg')

In [65]:
ar.shape


(4159, 3502, 3)

In [66]:
grar = cv2.cvtColor(ar, cv2.COLOR_BGR2GRAY)


In [67]:
rszar = cv2.resize(grar, (8, 8))


In [68]:
far = rszar.reshape(1, 64)


In [69]:
far


array([[205, 209,  44,  36,  57, 144,  27, 194, 143,  29,  58, 165, 186,
        183,  48, 210, 170,  30,  81, 141, 169, 180, 166, 179, 199, 101,
        113,  79, 169, 112, 179, 198, 212, 116, 111,  72, 205, 109, 194,
        218, 221,  47, 127,  46, 178, 173, 178, 173, 215, 199, 128,  57,
         96, 153, 131, 152, 219, 210,  34,  94, 169, 120,  83, 139]],
      dtype=uint8)

In [70]:
fimg = torch.FloatTensor(far)


In [71]:
model(fimg)


tensor([[-224.5794, -101.3662,  238.1218]], grad_fn=<AddmmBackward0>)

In [72]:
sfx = torch.softmax(model(fimg), dim=1)


In [73]:
torch.argmax(sfx, dim=1)


tensor([2])